config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :users, path: 'users', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    :omniauth_callbacks => "users/omniauth_callbacks"
    
  }

  resources :users, only: [:show]

  devise_for :admins, path: 'administrator', skip: [:registrations], controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    unlocks: 'admin/unlocks',
    confimations: 'admin/confimations'
  }

    
  #   member do
  #     post :pay_with_paypal
  #     get  :process_paypal_payment
  #   end

  resource :payments


  resources :publications do
    resources :califications
    resources :donations do 
      post :capture, on: :collection
      get :success, on: :collection
      post :pay, on: :member
      get :checkout, on: :member
    end
  end
  
  namespace :admin do
    get '', to: 'admins#index'
    resources :reports, only: [:index]
    resources :admins
    resources :users
    resources :publications

  end

  root to: 'landing#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/publication.rb
class Publication < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many_attached :documents
  has_many :califications, dependent: :destroy
  has_many :donations, dependent: :destroy
  has_many :payments


  validates :image, attached: true, content_type: ['image/png', 'image/jpg', 'image/jpeg']


  def confirmed_donations_amount
    donations.confirmed.sum(:amount)
  end


  def check_status_amount
    if amountoraise <= confirmed_donations_amount
      update(available: false)
    end
  end
end

app/controllers/admin/publications_controller.rb
class Admin::PublicationsController < Admin::BaseController
    def index
        @publication = Publication.all
    end

    def new
        @publication = Publication.new
    end

    def edit
 
    end
   
    def update
        respond_to do |format|
            if @publication.update(user_params)
              format.html { redirect_to admin_path, notice: "publication was successfully updated." }
              format.json { render :admin, status: :ok, location: @publication }
            else
              format.html { render :edit, status: :unprocessable_entity }
              format.json { render json: @user.errors, status: :unprocessable_entity }
            end
          end

    end

  

    def create
        @publication = Publication.new(publication)

        respond_to do |format|
            if @publication.save
                PostMailer.publication_create.delivery_later
                format.html { redirect_to @publication, notice: "publication was successfully created." }
                format.json { render :show, status: :created, location: @publication }
            else
                format.html { render :new, status: :unprocessable_entity }
                format.json { render json: @publication.errors, status: :unprocessable_entity }
            end
        end
    end


    private

    def publication_params
        params.require(:publication).permit(:name, :age, :amountoraise, :amountcollected, :user_id)
    end

   
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: %i[ show ]
  before_action :authenticate_user!
  before_action :set_publication_currentuser, only: %i[ edit update destroy ]


  # GET /publications or /publications.json
  def index
    @q = Publication.ransack(params[:q])
    @publications = @q.result(distinct: true)
  end

  # GET /publications/1 or /publications/1.json
  def show
  end

  # GET /publications/new
  def new
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications or /publications.json
  def create
    @user = current_user
    @publication = @user.publications.new(publication_params)

    respond_to do |format|
      if @publication.save
        PublicationsMailer.publication_create.deliver_later
        format.html { redirect_to @publication, notice: "Publication was successfully created." }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1 or /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to @publication, notice: "Publication was successfully updated." }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1 or /publications/1.json
  def destroy
    @publication.destroy
    respond_to do |format|
      format.html { redirect_to publications_url, notice: "Publication was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def set_publication_currentuser
    @publication = current_user.publications.find(params[:id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def publication_params
      params.require(:publication).permit(:name, :age, :image, :description, :amountoraise, :amountcollected, :califications, :user_id, documents: [])
    end
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/_form.html.erb
<div class="container">
  <% if signed_in? %>

  <%= form_with(model: publication, local: true) do |form| %>
    <% if publication.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

        <ul>
        <% publication.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field mb-3">
      <h4><%= form.label :name %></h4>
      <input class="form-control" <%= form.text_field :name %>
    </div>

    <div class="field mb-3 ">
      <h4><%= form.label :age %></h4>
      <input class="form-control" <%= form.number_field :age %>
    </div>
    
    <div class="field mb-3">
      <div class="field">
      <h4><%= form.label :image %></h4>
      <input class="form-control" type="file" id="formFile" <%= form.file_field :image %>
    </div>

    <div class="field mb-3">
      <h4><%= form.label :description %></h4>
      <textarea class="form-control " <%= form.text_area :description %></textarea>
    </div>

      <div class="field mb-3">
        <h4><%= form.label :documents %></h4>
        <input class="form-control" type="file" id="formFile"<%= form.file_field :documents, multiple: true %>
      </div>

    <div class="field mb-3">
      <h4><%= form.label :amountoraise %></h4>
      <span class="form-control">$ <%= form.text_field :amountoraise %></span>
      
    </div> 
    
    <div class="actions">
      <%= form.submit class:"btn btn-dark" %>
    </div>
  <% end %>
  <% else %>
  <% end %>
</div>

app/views/publications/edit.html.erb
<div class="container">
    <h1>Editing Publication</h1>

    <%= render 'form', publication: @publication %>

    <%= link_to 'Show', @publication %> |
    <%= link_to 'Back', publications_path %>
</div>

app/views/publications/index.html.erb
 <br>
<div class="container">
  <% if signed_in? %>
    <%= link_to 'Create New Publication', new_publication_path, class: "btn btn-dark float-end"%>
  <%end%>  
</div>

  <tbody>
  <br>
  <br>
  <div class="container">

  <%= search_form_for @q do |f| %>
    <%= f.label :name %>
    <%= f.search_field :name_matches %>
    <%= f.submit %>
  <% end %>

    <h1 id="publications" class="text-center">Publications</h1>   
        <div class="row"> 
          <% @publications.each do |publication| %>
            <div class="col-6 col-md-4 py-2">
              <div class="card" style="width: 18rem;">
                <img src="<%= url_for(publication.image) %>" class="card-img-top" alt="Image Animal">
                <div class="card-body">
                    <h5 class="card-title text-end">Available: 
                      <% if publication.available %>
                        <i class="far fa-check-circle"> </i>
                      <%else%>
                        <i class="far fa-times-circle"></i>
                      <%end%>
                    </h5>
                    <h5 class="card-title"><%= publication.name%></h5>
                    <h5 class="card-title"><%= publication.califications.count%>
                     <% if calification(publication, current_user) %>
                        <td>
                            <%= link_to publication_calification_path(publication, calification(publication, current_user)), method: :delete do %>
                                <i class="fas fa-star"></i>
                            <% end %>
                        </td>
                        
                    <% else %>
                        <td>
                            <%= link_to publication_califications_path(publication), method: :post do %>
                                <i class="far fa-star"></i>
                            <% end %>
                        </td>
                    <% end %></h5>

                    
                    <ul class="list-group list-group-flush">
                      <li class="list-group-item">Age: <%= publication.age %></li>
                      <li class="list-group-item">Description: <%= publication.description %></li>
                      <li class="list-group-item">
                        <strong>Documents: </strong>
                        <ul>
                          <% publication.documents.each do |document| %>
                          <li>
                            <%= link_to document.blob.filename.to_s, document %>
                          </li>
                          <% end %>
                        </ul>
                      </li>
                      <li class="list-group-item">User: <%= image_tag(publication.user.profile_picture.attached? ? publication.user.profile_picture : 'default_profile_picture.png', class: "rounded-circle", width: "45", height: "45", data: {"bs-toggle":"tooltip", "bs-placement":"top"}, title:"Tooltip on top" ) %></li>
                      <li class="list-group-item">Email: <%= publication.user.email %></li>              
                      
                      <li class="list-group-item">Need: $<%= publication.amountoraise %></li>              
                      <li class="list-group-item">Donations: $<%= publication.confirmed_donations_amount %></li>
                      
                      <% if signed_in? %>
                          <li class="list-group-item">
                              <a href="#" class="card-link"><%= link_to 'Show', publication %></a>
                            <% if publication.user == current_user%>
                                <a href="#" class="card-link"><%= link_to 'Edit', edit_publication_path(publication) %></a>
                            <% end%>
                          </li>
                      <strong class="text-center"><%= link_to 'View donations', publication_donations_path(publication) %> </strong>
                      <%end%>  
                    </ul>
                </div>  
              </div>    
            </div>  
            <% end %>  
      </div>
      </div>    
  </tbody>
<br>

app/views/publications/new.html.erb
<br>
<div class="container">
    <h1>New Publication</h1>
</div>

<%= render 'form', publication: @publication %>

<%= link_to 'Back', publications_path %>

app/views/publications/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>



</div>



<div class="container py-4">
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-body">
              <div class="row">
              <img class="w-100 border-radius-lg shadow-lg mx-auto" src="<%= url_for(@publication.image) %>" alt="chair">
                <div src="" class="col-xl-5 col-lg-6 text-center">
                  </div>
                  <!-- Root element of PhotoSwipe. Must have class pswp. -->
                  <div class="pswp" tabindex="-1" role="dialog" aria-hidden="true">
                    <!-- Background of PhotoSwipe.
It's a separate element, as animating opacity is faster than rgba(). -->
                    <div class="pswp__bg"></div>
                    <!-- Slides wrapper with overflow:hidden. -->
                    <div class="pswp__scroll-wrap">
                      <!-- Container that holds slides. PhotoSwipe keeps only 3 slides in DOM to save memory. -->
                      <!-- don't modify these 3 pswp__item elements, data is added later on. -->
                      <div class="pswp__container">
                        <div class="pswp__item"></div>
                        <div class="pswp__item"></div>
                        <div class="pswp__item"></div>
                      </div>
                      <!-- Default (PhotoSwipeUI_Default) interface on top of sliding area. Can be changed. -->
                      <div class="pswp__ui pswp__ui--hidden">
                        <div class="pswp__top-bar">
                          <!--  Controls are self-explanatory. Order can be changed. -->
                          <div class="pswp__counter"></div>
                          
                          <!-- Preloader demo https://codepen.io/dimsemenov/pen/yyBWoR -->
                          <!-- element will get class pswp__preloader--active when preloader is running -->
                          <div class="pswp__preloader">
                            <div class="pswp__preloader__icn">
                              <div class="pswp__preloader__cut">
                                <div class="pswp__preloader__donut"></div>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
                          <div class="pswp__share-tooltip"></div>
                        </div>
                        <div class="pswp__caption">
                          <div class="pswp__caption__center"></div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-lg-5 mx-auto">
                  <h2 class="mt-lg-0 mt-4"><%= @publication.name %></h2>
                  <br>
                  <h6 class="mb-0 mt-3">Age:</h6>
                  <h5><%= @publication.age%></h5>
            
                  <h6 class="mb-0 mt-3">Amount to raise:</h6>
                  <h5>$<%= @publication.amountoraise%></h5>
              
                  <h6 class="mb-0 mt-3">Amount to collected:</h6>
                  <h5>$<%= @publication.confirmed_donations_amount %></h5>
                 
                  <h6 class="mt-4">Description:</h6>
                  <%= @publication.description %>
                  <h6 class="mt-4">User:</h6>
                  <%= @publication.user.email %>

                  </div>
                  <%if @publication.user == current_user%>
                    <div class="text-end">
                    <%= link_to 'Edit', edit_publication_path(@publication) %> 
                  <%end%>
                      <%= link_to 'Back', publications_path%>
                    </div>
                  
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>