config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :users, path: 'users', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    :omniauth_callbacks => "users/omniauth_callbacks"
    
  }

  resources :users, only: [:show]

  devise_for :admins, path: 'administrator', skip: [:registrations], controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    unlocks: 'admin/unlocks',
    confimations: 'admin/confimations'
  }

    
  #   member do
  #     post :pay_with_paypal
  #     get  :process_paypal_payment
  #   end

  resource :payments


  resources :publications do
    resources :califications
    resources :donations do 
      post :capture, on: :collection
      get :success, on: :collection
      post :pay, on: :member
      get :checkout, on: :member
    end
  end
  
  namespace :admin do
    get '', to: 'admins#index'
    resources :reports, only: [:index]
    resources :admins
    resources :users
    resources :publications

  end

  root to: 'landing#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :publication
  belongs_to :user
  has_many :payments

  after_save :check_publications_status, if: :paid_completed?


  scope :confirmed, -> { where(paid: true) }

  validates :amount, presence: true


  private

  def paid_completed?
    paid
  end

  def check_publications_status
    publication.check_status_amount
  end




end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :set_publication
  before_action :set_donation, only: %i[ show edit update destroy checkout pay ]
  skip_before_action :verify_authenticity_token
  before_action :paypal_init, :except => [:index]


  def index
      @donations = @publication.donations.confirmed
  end

  def show
  end

    # GET 
  def new
    @donation = @publication.donations.new
  end

  # GET 
  def edit
  end

  # POST 
  def create
    @donation = @publication.donations.new(donation_params)
    @donation.user = current_user

    respond_to do |format|
      if @donation.save
        format.html { redirect_to checkout_publication_donation_path(@publication, @donation) }
        format.json { render :show, status: :created, location: @donation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def update
    respond_to do |format|
      if @donation.update(donation_params)
        format.html { redirect_to [@publication, @donation], notice: "Donation was successfully updated." }
        format.json { render :show, status: :ok, location: @donation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE 
  def destroy
    @donation.destroy
    respond_to do |format|
      format.html { redirect_to publication_donations_path(@publication), notice: "Donation was successfully destroyed." }
      format.json { head :no_content }
      format.js {}
    end
  end

  def checkout
  end


  def pay
    amount = @donation.amount
    request = PayPalCheckoutSdk::Orders::OrdersCreateRequest::new
    request.request_body({
      :intent => 'CAPTURE',
      :purchase_units => [
        {
          :amount => {
            :currency_code => 'USD',
            :value => amount
          }
        }
      ]
    })
    begin
      response = @client.execute request
      @donation.token = response.result.id
      # donation.status = 'pending' (crear enum status: 'pending', 'confirmed', 'failed')
      if @donation.save
        return render json: {token: response.result.id}, status: :ok
      end
    rescue PayPalHttp::HttpError => _
      # HANDLE THE ERROR
    end
  end

  def capture
    token = params[:token]
    request = PayPalCheckoutSdk::Orders::OrdersCaptureRequest::new token
    begin
      response = @client.execute request
      donation = Donation.find_by(token: token)
      donation.paid = response.result.status == 'COMPLETED'
      if donation.save
        return render :json => {:status => response.result.status}, :status => :ok
      end
    rescue PayPalHttp::HttpError => _
      # HANDLE THE ERROR
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donation
      @donation =  @publication.donations.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def donation_params
      params.require(:donation).permit(:amount)
    end

    def set_publication
        @publication = Publication.find(params[:publication_id])
    end

    
  def paypal_init
    client_id = 'AYW1NlwxvS3yXvwhvSLs1hQoWmF77A8mVy4nUHEgm2izlaCB3lVIuPD9oO5O4ZXusZqnTlonaCB6FICF'
    client_secret = 'EHJ_FigLj4LG7FhyoK45rVOgCmX-lr5r12CWBhBwup2sNu0T0h-9ukpMbPMbovY4_i8guvZeErzGxYxC'
    environment = PayPal::SandboxEnvironment.new client_id, client_secret
    @client = PayPal::PayPalHttpClient.new environment
  end
end

app/views/donations/_form.html.erb
<%= form_with(model: donation, url: [@publication, donation], local: true) do |form| %>
  <% if donation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(donation.errors.count, "error") %> prohibited this donation from being saved:</h2>

      <ul>
      <% donation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field mb-3"> 
    <%= form.label :amount %>
    <input class="form-control" <%= form.number_field  :amount %>
  </div>
  

  <div class="actions">
    <%= form.submit class:"btn btn-dark" %>
  </div>
<% end %>

app/views/donations/checkout.html.erb
    <div class="container">
    <br>
        <h5>Monto a pagar:  $<%= @donation.amount %></h5>
        
        <div id="paypal-button-container"></div>
        <script>
        paypal.Buttons({
            env: 'sandbox', // Valid values are sandbox and live.
            createOrder: async () => {
                const response = await fetch("<%= pay_publication_donation_path(@publication, @donation) %>", {method: 'POST'});
                const responseData = await response.json();
                return responseData.token;
            },
            onApprove: async (data) => {
                const response = await fetch("<%= capture_publication_donations_path(@publication) %>", {
                    method: 'POST',
                    headers: {
                    'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({token: data.orderID})
                });
                const responseData = await response.json();
                if (responseData.status === 'COMPLETED') {
                    window.location.replace("<%= success_publication_donations_path(@publication) %>");
                } else {
                    alert('error intentalo nuevamente')
                }
            }
        }).render('#paypal-button-container');
        </script>
    </div>

app/views/donations/edit.html.erb
<div class="container">
    <h1>Editing Donation</h1>

    <%= render 'form', donation: @donation %>

    <%= link_to 'Show', publication_donation_path(@publication, @donation) %> 
    <%= link_to 'Back', publication_donations_path(@publication) %>
</div>

app/views/donations/fail.html.erb
<div class= "container">
    El pago no fue procesado, intentelo nuevamente
</div>

app/views/donations/index.html.erb
<p id="notice"><%= notice %></p>


<div class="container py-4">
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-body">
              <div class="row">
              
                  <!-- Root element of PhotoSwipe. Must have class pswp. -->
                  <div class="pswp" tabindex="-1" role="dialog" aria-hidden="true">
                    <!-- Background of PhotoSwipe.
It's a separate element, as animating opacity is faster than rgba(). -->
                    <div class="pswp__bg"></div>
                    <!-- Slides wrapper with overflow:hidden. -->
                    <div class="pswp__scroll-wrap">
                  
                      <!-- Default (PhotoSwipeUI_Default) interface on top of sliding area. Can be changed. -->
                      <div class="pswp__ui pswp__ui--hidden">
                        <div class="pswp__top-bar">
                          <!--  Controls are self-explanatory. Order can be changed. -->
                          <div class="pswp__counter"></div>
                          
                          <!-- Preloader demo https://codepen.io/dimsemenov/pen/yyBWoR -->
                          <!-- element will get class pswp__preloader--active when preloader is running -->
                          <div class="pswp__preloader">
                            <div class="pswp__preloader__icn">
                              <div class="pswp__preloader__cut">
                                <div class="pswp__preloader__donut"></div>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
                          <div class="pswp__share-tooltip"></div>
                        </div>
                        <div class="pswp__caption">
                          <div class="pswp__caption__center"></div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-lg-5 mx-auto">
                  <h2 class="mt-lg-0 mt-4">Donations for <%= @publication.name%></h2>
                  <br>
                <% @donations.each do |donation| %>
                    <ul>
                    <li><h6 class="mb-0 mt-3">Amount to donate:</h6><h5>$<%= donation.amount%></h5></li>

                    <li><h6 class="mb-0 mt-3">User: </h6>
                    <h5><%= donation.user.email%></h5></li>
                    </ul> 
                <% end %>
                   
                  </div>
                  <div class="text-end">
                    <% if @publication.available %>
                      <%= link_to 'New Donation', new_publication_donation_path(@publication) %>  
                    <%else%>
                      <h6 class="fw-bold"><%= 'No se permiten más devoluciones ¡Cumplimos la meta!' %></h6>              
                    <%end%>
                    <br>
                    <%= link_to 'Back', publications_path(@publication) %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

app/views/donations/new.html.erb
<br>
<div class="container">
    <h1>New Donation</h1>

    <%= render 'form', donation: @donation %>

    <%= link_to 'Back', publication_donations_path(@publication) %>
</div>

app/views/donations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_publication_donation_path(@publication, @donation) %> 
<%= link_to 'Back', publication_donations_path(@publication) %>

app/views/donations/success.html.erb
<div class="container">
<br>
<h4 class="fw-bold">Pago procesado correctamente</h4>
<%= link_to 'Volver a la publicación', publication_path(@publication)%>
</div>