config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :users, path: 'users', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    :omniauth_callbacks => "users/omniauth_callbacks"
    
  }

  resources :users, only: [:show]

  devise_for :admins, path: 'administrator', skip: [:registrations], controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    unlocks: 'admin/unlocks',
    confimations: 'admin/confimations'
  }

    
  #   member do
  #     post :pay_with_paypal
  #     get  :process_paypal_payment
  #   end

  resource :payments


  resources :publications do
    resources :califications
    resources :donations do 
      post :capture, on: :collection
      get :success, on: :collection
      post :pay, on: :member
      get :checkout, on: :member
    end
  end
  
  namespace :admin do
    get '', to: 'admins#index'
    resources :reports, only: [:index]
    resources :admins
    resources :users
    resources :publications

  end

  root to: 'landing#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admin/admins/index.html.erb
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4"><div class="chartjs-size-monitor"><div class="chartjs-size-monitor-expand"><div class=""></div></div><div class="chartjs-size-monitor-shrink"><div class=""></div></div></div>
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Administrators</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <%= link_to 'Create', new_admin_admin_path, class: "btn btn-sm btn-outline-secondary" %>
        </div>
      </div>
      <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Email</th>
              <th scope="col">Created At</th>
            </tr>
          </thead>
          <tbody>
          <% @admins.each do |admin| %>
            <tr>
              <td><%= admin.id %></td>
              <td><%= admin.email %></td>
              <td><%= admin.created_at %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </main>

app/views/admin/admins/new.html.erb
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4"><div class="chartjs-size-monitor"><div class="chartjs-size-monitor-expand"><div class=""></div></div><div class="chartjs-size-monitor-shrink"><div class=""></div></div></div>
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Administrators</h1>
      </div>

      <%= form_for :admin, url: admin_admins_path do |f| %>
        <div class="mb-3">
          <%= f.email_field :email, autofocus: true, autocomplete: "email", placeholder: "name@example.com", class: "form-control" %>
          <%= f.label :email %>
        </div>

        <div class="mb-3">
          <%= f.password_field :password, autocomplete: "new-password", class: "form-control" %>
          <%= f.label :password %>
        </div>

        <%= f.submit "Sign in", class: "btn btn-sm btn-outline-secondary" %>
      <% end %>
      
    </main>